export const scenarios = {
  'web-basics': {
    title: 'Web himoya sarlavhalari',
    category: 'Web Security',
    briefing: 'training.local javobini tekshiring va zamonaviy brauzerda yuklanadigan resurslarni cheklovchi yetishmayotgan himoya sarlavhasini toping.',
    objective: 'Yetishmayotgan HTTP sarlavhasi nomini javob maydoniga kiriting.',
    commands: {
      'help': 'Mavjud buyruqlar:\n  curl -I http://training.local\n  cat mission.txt\n  clear',
      'cat mission.txt': 'Vazifa: server javobidagi himoya sarlavhalarini audit qiling.',
      'curl -i http://training.local': 'HTTP/1.1 200 OK\nServer: training-gateway\nX-Content-Type-Options: nosniff\nReferrer-Policy: no-referrer\nX-Frame-Options: DENY\nContent-Type: text/html',
    },
    answers: ['content-security-policy', 'content security policy', 'csp'],
    hint: 'Bu sarlavha script, style va boshqa resurslarning qayerdan yuklanishini boshqaradi.',
    success: 'CSP aniqlandi. Brauzer uchun qatlamli himoya rejasiga yana bir nazorat qo‘shildi.',
  },
  'log-investigation': {
    title: 'Shubhali login izlari',
    category: 'Forensics',
    briefing: 'Autentifikatsiya logida qisqa vaqt ichida takroriy muvaffaqiyatsiz urinishlar bor. Manba IP’ni aniqlang.',
    objective: 'Eng ko‘p muvaffaqiyatsiz urinish yuborgan IP manzilini kiriting.',
    commands: {
      'help': 'Mavjud buyruqlar:\n  cat /var/log/auth.log\n  grep Failed /var/log/auth.log\n  clear',
      'cat /var/log/auth.log': '09:14:03 sshd Accepted publickey for student from 198.51.100.18\n09:16:11 sshd Failed password for admin from 203.0.113.42\n09:16:14 sshd Failed password for admin from 203.0.113.42\n09:16:18 sshd Failed password for root from 203.0.113.42\n09:18:07 sshd Accepted publickey for mentor from 198.51.100.22',
      'grep failed /var/log/auth.log': '09:16:11 Failed password — 203.0.113.42\n09:16:14 Failed password — 203.0.113.42\n09:16:18 Failed password — 203.0.113.42',
    },
    answers: ['203.0.113.42'],
    hint: 'Failed password yozuvlarini bir manba bo‘yicha guruhlang.',
    success: 'Manba aniqlandi. Keyingi xavfsiz qadam — bloklashdan oldin hodisani tasdiqlash va audit izini saqlash.',
  },
  'linux-permissions': {
    title: 'Linux fayl huquqlari',
    category: 'Linux',
    briefing: 'Maxfiy konfiguratsiya faylini barcha foydalanuvchilar o‘qiy va o‘zgartira olmoqda. Faqat egasi o‘qib-yoza oladigan rejimni tanlang.',
    objective: 'Kerakli chmod buyrug‘ini to‘liq kiriting.',
    commands: {
      'help': 'Mavjud buyruqlar:\n  ls -l /srv/app/config.env\n  stat /srv/app/config.env\n  clear',
      'ls -l /srv/app/config.env': '-rw-rw-rw- 1 app app 240 Jul 19 10:24 /srv/app/config.env',
      'stat /srv/app/config.env': 'Access: (0666/-rw-rw-rw-)  Uid: app  Gid: app',
    },
    answers: ['chmod 600 /srv/app/config.env'],
    hint: '6 — o‘qish va yozish; qolgan ikki guruhda ruxsat bo‘lmasin.',
    success: 'Fayl 0600 rejimiga keltirildi. Maxfiy konfiguratsiya faqat servis egasiga ochiq.',
  },
  'container-health': {
    title: 'Container health check',
    category: 'Docker',
    briefing: 'api konteyneri running holatida, lekin yuk balanslagich undan trafikni qaytaryapti. Diagnostika signalini toping.',
    objective: 'Dockerfile’da servis sog‘lomligini avtomatik tekshiradigan direktiva nomini kiriting.',
    commands: {
      'help': 'Mavjud buyruqlar:\n  docker ps\n  docker inspect api\n  docker logs api\n  clear',
      'docker ps': 'CONTAINER   IMAGE            STATUS\napi         hackpro/api:1  Up 8 minutes (unhealthy)',
      'docker inspect api': 'Health.Status: unhealthy\nHealth.Log: GET /health → connection refused\nRestartCount: 0',
      'docker logs api': 'server listening on :3000\nwarning: /health endpoint not configured',
    },
    answers: ['healthcheck', 'health check'],
    hint: 'Dockerfile’da CMD va ENTRYPOINT bilan bir qatorda sog‘lomlikni tekshiruvchi maxsus direktiva mavjud.',
    success: 'HEALTHCHECK topildi. Endi deploy faqat haqiqatan so‘rov qabul qilayotgan konteynerga trafik yuboradi.',
  },
  'cicd-guard': {
    title: 'CI/CD xavfsizlik darvozasi',
    category: 'DevOps',
    briefing: 'Pipeline build’dan keyin darhol production deploy qilmoqda. Xatoli kodni to‘xtatadigan majburiy bosqich yetishmaydi.',
    objective: 'Deploy oldidan qo‘shilishi kerak bo‘lgan asosiy bosqich nomini kiriting.',
    commands: {
      'help': 'Mavjud buyruqlar:\n  cat pipeline.yml\n  show history\n  clear',
      'cat pipeline.yml': 'stages:\n  - build\n  - deploy\n\nbuild: npm run build\ndeploy: ./deploy-production.sh',
      'show history': '#142 deploy failed — UI regression\n#141 deploy failed — lint error\n#140 deploy successful',
    },
    answers: ['test', 'tests', 'testing'],
    hint: 'Build natijasi productionga chiqishdan oldin avtomatik tekshiruvdan o‘tishi kerak.',
    success: 'Test darvozasi qo‘shildi. Xatoli build production bosqichiga o‘tmaydi.',
  },
  'k8s-recovery': {
    title: 'Kubernetes pod tiklash',
    category: 'Kubernetes',
    briefing: 'Pod Running holatida, ammo Service unga juda erta trafik yubormoqda va 503 javoblar paydo bo‘lmoqda.',
    objective: 'Pod trafik qabul qilishga tayyorligini bildiradigan Kubernetes probe nomini kiriting.',
    commands: {
      'help': 'Mavjud buyruqlar:\n  kubectl get pods\n  kubectl describe pod api-7d9f\n  kubectl logs api-7d9f\n  clear',
      'kubectl get pods': 'NAME       READY   STATUS    RESTARTS\napi-7d9f   1/1     Running   0',
      'kubectl describe pod api-7d9f': 'Containers: api\nState: Running\nReadiness: not configured\nEvents: Service routed traffic 2s after container start',
      'kubectl logs api-7d9f': 'booting migrations...\nloading models...\nserver ready after 18s',
    },
    answers: ['readinessprobe', 'readiness probe', 'readiness'],
    hint: 'Liveness jarayon tirikligini, boshqa probe esa trafik qabul qilishga tayyorligini bildiradi.',
    success: 'readinessProbe aniqlandi. Service endi pod tayyor bo‘lmaguncha unga trafik yubormaydi.',
  },
};
